// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: driver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Driver_NewDriver_FullMethodName    = "/v1.Driver/NewDriver"
	Driver_DetailDriver_FullMethodName = "/v1.Driver/DetailDriver"
	Driver_UpdDriver_FullMethodName    = "/v1.Driver/UpdDriver"
)

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverClient interface {
	NewDriver(ctx context.Context, in *NewDriverReq, opts ...grpc.CallOption) (*NewDriverResp, error)
	DetailDriver(ctx context.Context, in *DetailDriverReq, opts ...grpc.CallOption) (*DetailDriverResp, error)
	UpdDriver(ctx context.Context, in *UpdDriverReq, opts ...grpc.CallOption) (*UpdDriverResp, error)
}

type driverClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverClient(cc grpc.ClientConnInterface) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) NewDriver(ctx context.Context, in *NewDriverReq, opts ...grpc.CallOption) (*NewDriverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewDriverResp)
	err := c.cc.Invoke(ctx, Driver_NewDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) DetailDriver(ctx context.Context, in *DetailDriverReq, opts ...grpc.CallOption) (*DetailDriverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetailDriverResp)
	err := c.cc.Invoke(ctx, Driver_DetailDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) UpdDriver(ctx context.Context, in *UpdDriverReq, opts ...grpc.CallOption) (*UpdDriverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdDriverResp)
	err := c.cc.Invoke(ctx, Driver_UpdDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServer is the server API for Driver service.
// All implementations must embed UnimplementedDriverServer
// for forward compatibility.
type DriverServer interface {
	NewDriver(context.Context, *NewDriverReq) (*NewDriverResp, error)
	DetailDriver(context.Context, *DetailDriverReq) (*DetailDriverResp, error)
	UpdDriver(context.Context, *UpdDriverReq) (*UpdDriverResp, error)
	mustEmbedUnimplementedDriverServer()
}

// UnimplementedDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServer struct{}

func (UnimplementedDriverServer) NewDriver(context.Context, *NewDriverReq) (*NewDriverResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewDriver not implemented")
}
func (UnimplementedDriverServer) DetailDriver(context.Context, *DetailDriverReq) (*DetailDriverResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetailDriver not implemented")
}
func (UnimplementedDriverServer) UpdDriver(context.Context, *UpdDriverReq) (*UpdDriverResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdDriver not implemented")
}
func (UnimplementedDriverServer) mustEmbedUnimplementedDriverServer() {}
func (UnimplementedDriverServer) testEmbeddedByValue()                {}

// UnsafeDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServer will
// result in compilation errors.
type UnsafeDriverServer interface {
	mustEmbedUnimplementedDriverServer()
}

func RegisterDriverServer(s grpc.ServiceRegistrar, srv DriverServer) {
	// If the following call pancis, it indicates UnimplementedDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Driver_ServiceDesc, srv)
}

func _Driver_NewDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewDriverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).NewDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_NewDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).NewDriver(ctx, req.(*NewDriverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_DetailDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailDriverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).DetailDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_DetailDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).DetailDriver(ctx, req.(*DetailDriverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_UpdDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdDriverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).UpdDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Driver_UpdDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).UpdDriver(ctx, req.(*UpdDriverReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Driver_ServiceDesc is the grpc.ServiceDesc for Driver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Driver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewDriver",
			Handler:    _Driver_NewDriver_Handler,
		},
		{
			MethodName: "DetailDriver",
			Handler:    _Driver_DetailDriver_Handler,
		},
		{
			MethodName: "UpdDriver",
			Handler:    _Driver_UpdDriver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver.proto",
}
