// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.11
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendTextMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextMessageReq) Reset() {
	*x = SendTextMessageReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextMessageReq) ProtoMessage() {}

func (x *SendTextMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextMessageReq.ProtoReflect.Descriptor instead.
func (*SendTextMessageReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *SendTextMessageReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SendTextMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextMessageResp) Reset() {
	*x = SendTextMessageResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextMessageResp) ProtoMessage() {}

func (x *SendTextMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextMessageResp.ProtoReflect.Descriptor instead.
func (*SendTextMessageResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type RegisterReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phone            string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verificationCode,proto3" json:"verificationCode,omitempty"`
	Password         string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterReq) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phone            string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	VerificationCode string                 `protobuf:"bytes,3,opt,name=verificationCode,proto3" json:"verificationCode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ForgotPasswordReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phone            string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verificationCode,proto3" json:"verificationCode,omitempty"`
	Password         string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword  string                 `protobuf:"bytes,4,opt,name=confirmPassword,proto3" json:"confirmPassword,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForgotPasswordReq) Reset() {
	*x = ForgotPasswordReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordReq) ProtoMessage() {}

func (x *ForgotPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordReq.ProtoReflect.Descriptor instead.
func (*ForgotPasswordReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *ForgotPasswordReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ForgotPasswordReq) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *ForgotPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ForgotPasswordReq) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type ForgotPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResp) Reset() {
	*x = ForgotPasswordResp{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResp) ProtoMessage() {}

func (x *ForgotPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResp.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

type CompleteInformationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Cover         string                 `protobuf:"bytes,2,opt,name=cover,proto3" json:"cover,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex           string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	RealName      string                 `protobuf:"bytes,5,opt,name=realName,proto3" json:"realName,omitempty"`
	IdCard        string                 `protobuf:"bytes,6,opt,name=idCard,proto3" json:"idCard,omitempty"`
	BirthdayTime  string                 `protobuf:"bytes,7,opt,name=birthdayTime,proto3" json:"birthdayTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteInformationReq) Reset() {
	*x = CompleteInformationReq{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteInformationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteInformationReq) ProtoMessage() {}

func (x *CompleteInformationReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteInformationReq.ProtoReflect.Descriptor instead.
func (*CompleteInformationReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteInformationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompleteInformationReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CompleteInformationReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CompleteInformationReq) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *CompleteInformationReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *CompleteInformationReq) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *CompleteInformationReq) GetBirthdayTime() string {
	if x != nil {
		return x.BirthdayTime
	}
	return ""
}

type CompleteInformationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteInformationResp) Reset() {
	*x = CompleteInformationResp{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteInformationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteInformationResp) ProtoMessage() {}

func (x *CompleteInformationResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteInformationResp.ProtoReflect.Descriptor instead.
func (*CompleteInformationResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

type StudentVerificationReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SchoolName     string                 `protobuf:"bytes,2,opt,name=schoolName,proto3" json:"schoolName,omitempty"`
	StudentId      string                 `protobuf:"bytes,3,opt,name=studentId,proto3" json:"studentId,omitempty"`
	EnrollmentYear string                 `protobuf:"bytes,4,opt,name=enrollmentYear,proto3" json:"enrollmentYear,omitempty"`
	StudentIdPhoto string                 `protobuf:"bytes,5,opt,name=studentIdPhoto,proto3" json:"studentIdPhoto,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudentVerificationReq) Reset() {
	*x = StudentVerificationReq{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentVerificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentVerificationReq) ProtoMessage() {}

func (x *StudentVerificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentVerificationReq.ProtoReflect.Descriptor instead.
func (*StudentVerificationReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *StudentVerificationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StudentVerificationReq) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

func (x *StudentVerificationReq) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentVerificationReq) GetEnrollmentYear() string {
	if x != nil {
		return x.EnrollmentYear
	}
	return ""
}

func (x *StudentVerificationReq) GetStudentIdPhoto() string {
	if x != nil {
		return x.StudentIdPhoto
	}
	return ""
}

type StudentVerificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentVerificationResp) Reset() {
	*x = StudentVerificationResp{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentVerificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentVerificationResp) ProtoMessage() {}

func (x *StudentVerificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentVerificationResp.ProtoReflect.Descriptor instead.
func (*StudentVerificationResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

type PersonalCenterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalCenterReq) Reset() {
	*x = PersonalCenterReq{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalCenterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalCenterReq) ProtoMessage() {}

func (x *PersonalCenterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalCenterReq.ProtoReflect.Descriptor instead.
func (*PersonalCenterReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *PersonalCenterReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PersonalCenterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Cover         string                 `protobuf:"bytes,2,opt,name=cover,proto3" json:"cover,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex           string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	BirthdayTime  string                 `protobuf:"bytes,5,opt,name=birthdayTime,proto3" json:"birthdayTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalCenterResp) Reset() {
	*x = PersonalCenterResp{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalCenterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalCenterResp) ProtoMessage() {}

func (x *PersonalCenterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalCenterResp.ProtoReflect.Descriptor instead.
func (*PersonalCenterResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *PersonalCenterResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PersonalCenterResp) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *PersonalCenterResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PersonalCenterResp) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *PersonalCenterResp) GetBirthdayTime() string {
	if x != nil {
		return x.BirthdayTime
	}
	return ""
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *LogoutReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LogoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResp) Reset() {
	*x = LogoutResp{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResp) ProtoMessage() {}

func (x *LogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResp.ProtoReflect.Descriptor instead.
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x02v1\"*\n" +
	"\x12SendTextMessageReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"\x15\n" +
	"\x13SendTextMessageResp\"k\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12*\n" +
	"\x10verificationCode\x18\x02 \x01(\tR\x10verificationCode\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x1e\n" +
	"\fRegisterResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12*\n" +
	"\x10verificationCode\x18\x03 \x01(\tR\x10verificationCode\"\x1b\n" +
	"\tLoginResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9b\x01\n" +
	"\x11ForgotPasswordReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12*\n" +
	"\x10verificationCode\x18\x02 \x01(\tR\x10verificationCode\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12(\n" +
	"\x0fconfirmPassword\x18\x04 \x01(\tR\x0fconfirmPassword\"\x14\n" +
	"\x12ForgotPasswordResp\"\xcc\x01\n" +
	"\x16CompleteInformationReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05cover\x18\x02 \x01(\tR\x05cover\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\x1a\n" +
	"\brealName\x18\x05 \x01(\tR\brealName\x12\x16\n" +
	"\x06idCard\x18\x06 \x01(\tR\x06idCard\x12\"\n" +
	"\fbirthdayTime\x18\a \x01(\tR\fbirthdayTime\"\x19\n" +
	"\x17CompleteInformationResp\"\xbe\x01\n" +
	"\x16StudentVerificationReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"schoolName\x18\x02 \x01(\tR\n" +
	"schoolName\x12\x1c\n" +
	"\tstudentId\x18\x03 \x01(\tR\tstudentId\x12&\n" +
	"\x0eenrollmentYear\x18\x04 \x01(\tR\x0eenrollmentYear\x12&\n" +
	"\x0estudentIdPhoto\x18\x05 \x01(\tR\x0estudentIdPhoto\"\x19\n" +
	"\x17StudentVerificationResp\"+\n" +
	"\x11PersonalCenterReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\x92\x01\n" +
	"\x12PersonalCenterResp\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05cover\x18\x02 \x01(\tR\x05cover\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\"\n" +
	"\fbirthdayTime\x18\x05 \x01(\tR\fbirthdayTime\"#\n" +
	"\tLogoutReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\f\n" +
	"\n" +
	"LogoutResp2\xea\x03\n" +
	"\x04User\x12B\n" +
	"\x0fSendTextMessage\x12\x16.v1.SendTextMessageReq\x1a\x17.v1.SendTextMessageResp\x12-\n" +
	"\bRegister\x12\x0f.v1.RegisterReq\x1a\x10.v1.RegisterResp\x12$\n" +
	"\x05Login\x12\f.v1.LoginReq\x1a\r.v1.LoginResp\x12?\n" +
	"\x0eForgotPassword\x12\x15.v1.ForgotPasswordReq\x1a\x16.v1.ForgotPasswordResp\x12N\n" +
	"\x13CompleteInformation\x12\x1a.v1.CompleteInformationReq\x1a\x1b.v1.CompleteInformationResp\x12N\n" +
	"\x13StudentVerification\x12\x1a.v1.StudentVerificationReq\x1a\x1b.v1.StudentVerificationResp\x12?\n" +
	"\x0ePersonalCenter\x12\x15.v1.PersonalCenterReq\x1a\x16.v1.PersonalCenterResp\x12'\n" +
	"\x06Logout\x12\r.v1.LogoutReq\x1a\x0e.v1.LogoutRespB\x19Z\x17../../../internal/protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_user_proto_goTypes = []any{
	(*SendTextMessageReq)(nil),      // 0: v1.SendTextMessageReq
	(*SendTextMessageResp)(nil),     // 1: v1.SendTextMessageResp
	(*RegisterReq)(nil),             // 2: v1.RegisterReq
	(*RegisterResp)(nil),            // 3: v1.RegisterResp
	(*LoginReq)(nil),                // 4: v1.LoginReq
	(*LoginResp)(nil),               // 5: v1.LoginResp
	(*ForgotPasswordReq)(nil),       // 6: v1.ForgotPasswordReq
	(*ForgotPasswordResp)(nil),      // 7: v1.ForgotPasswordResp
	(*CompleteInformationReq)(nil),  // 8: v1.CompleteInformationReq
	(*CompleteInformationResp)(nil), // 9: v1.CompleteInformationResp
	(*StudentVerificationReq)(nil),  // 10: v1.StudentVerificationReq
	(*StudentVerificationResp)(nil), // 11: v1.StudentVerificationResp
	(*PersonalCenterReq)(nil),       // 12: v1.PersonalCenterReq
	(*PersonalCenterResp)(nil),      // 13: v1.PersonalCenterResp
	(*LogoutReq)(nil),               // 14: v1.LogoutReq
	(*LogoutResp)(nil),              // 15: v1.LogoutResp
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: v1.User.SendTextMessage:input_type -> v1.SendTextMessageReq
	2,  // 1: v1.User.Register:input_type -> v1.RegisterReq
	4,  // 2: v1.User.Login:input_type -> v1.LoginReq
	6,  // 3: v1.User.ForgotPassword:input_type -> v1.ForgotPasswordReq
	8,  // 4: v1.User.CompleteInformation:input_type -> v1.CompleteInformationReq
	10, // 5: v1.User.StudentVerification:input_type -> v1.StudentVerificationReq
	12, // 6: v1.User.PersonalCenter:input_type -> v1.PersonalCenterReq
	14, // 7: v1.User.Logout:input_type -> v1.LogoutReq
	1,  // 8: v1.User.SendTextMessage:output_type -> v1.SendTextMessageResp
	3,  // 9: v1.User.Register:output_type -> v1.RegisterResp
	5,  // 10: v1.User.Login:output_type -> v1.LoginResp
	7,  // 11: v1.User.ForgotPassword:output_type -> v1.ForgotPasswordResp
	9,  // 12: v1.User.CompleteInformation:output_type -> v1.CompleteInformationResp
	11, // 13: v1.User.StudentVerification:output_type -> v1.StudentVerificationResp
	13, // 14: v1.User.PersonalCenter:output_type -> v1.PersonalCenterResp
	15, // 15: v1.User.Logout:output_type -> v1.LogoutResp
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
